# Default setup is given for MySQL with ruby1.8. If you're running Redmine
# with MySQL and ruby1.9, replace the adapter name with `mysql2`.
# Examples for PostgreSQL and SQLite3 can be found at the end.

production:
  adapter:  mysql2
  database: <%= ENV['OPENSHIFT_APP_NAME'] %>
  host:     <%= ENV['OPENSHIFT_MYSQL_DB_HOST'] %>
  username: <%= ENV['OPENSHIFT_MYSQL_DB_USERNAME'] %>
  password: <%= ENV['OPENSHIFT_MYSQL_DB_PASSWORD'] %>
  port:     <%= ENV['OPENSHIFT_MYSQL_DB_PORT'] %>
  encoding: utf8

development:
  adapter:  sqlite3
  database: db/test.sqlite3
